/*
 * NagDialog.java
 *
 * Created on December 13, 2007, 4:56 PM
 */
package naughtyclock;

import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author  richard
 */
public class NagDialog extends javax.swing.JDialog {

    private int delay; // seconds to annoy user for

    /** Creates new form NagDialog */
    public NagDialog(java.awt.Frame parent, int d) {
        super(parent, true);
        this.delay = d;

        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        setAlwaysOnTop(true);

        ActionListener tickPerformer = new ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                if (delay >= 0) {

                    LaterButton.setText("" + delay);


                    delay--;
                } else {
                    LaterButton.setEnabled(true);
                    LaterButton.setText("Later");
                }

            }
        };
        new Timer(1000, tickPerformer).start();

        setVisible(true);





    }

    boolean showInBrowser(String url) {



        String os = System.getProperty("os.name").toLowerCase();
        Runtime rt = Runtime.getRuntime();
        try {
            if (os.indexOf("win") >= 0) {
                String[] cmd = new String[4];
                cmd[0] = "cmd.exe";
                cmd[1] = "/C";
                cmd[2] = "start";
                cmd[3] = url;
                rt.exec(cmd);
            } else if (os.indexOf("mac") >= 0) {
                rt.exec("open " + url);
            } else {
                //prioritized 'guess' of users' preference
                String[] browsers = {"epiphany", "firefox", "mozilla", "konqueror",
                    "netscape", "opera", "links", "lynx"
                };

                StringBuffer cmd = new StringBuffer();
                for (int i = 0; i < browsers.length; i++) {
                    cmd.append((i == 0 ? "" : " || ") + browsers[i] + " \"" + url + "\" ");
                }

                rt.exec(new String[]{"sh", "-c", cmd.toString()});

            }
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "\n\n The system failed to invoke your default web browser while attempting to access: \n\n " + url + "\n\n",
                    "Browser Error",
                    JOptionPane.WARNING_MESSAGE);

            return false;
        }
        return true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        yesButton = new javax.swing.JButton();
        RegisterButton = new javax.swing.JButton();
        LaterButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Naughty Clock is Beerware!");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Please buy the author a beer");

        yesButton.setText("Buy Now");
        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButtonActionPerformed(evt);
            }
        });

        RegisterButton.setText("Enter Registration Code");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        LaterButton.setText("Maybe Later");
        LaterButton.setEnabled(false);
        LaterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaterButtonActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("to make this nag screen go away");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("It will only cost you 3 quid!");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(RegisterButton)
                        .add(114, 114, 114)
                        .add(LaterButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 167, Short.MAX_VALUE)
                        .add(yesButton))
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(41, 41, 41)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel3)
                .add(41, 41, 41)
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 170, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(RegisterButton)
                    .add(yesButton)
                    .add(LaterButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButtonActionPerformed
        setAlwaysOnTop(false);
        showInBrowser("http://www.fantastic.me.uk/naughtybuy.html");
}//GEN-LAST:event_yesButtonActionPerformed

    private void LaterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaterButtonActionPerformed
        setVisible(false);
        dispose();
}//GEN-LAST:event_LaterButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        setAlwaysOnTop(false);
        try {
            RegisterDialog dialog = new RegisterDialog(null);
            if(dialog.getReturnStatus()==dialog.RET_CANCEL) return;
            String result = Utility.checkCode(dialog.getRegCode());//GEN-LAST:event_RegisterButtonActionPerformed
            if(!result.startsWith("NaughtyClock V1")) throw new Exception("Wrong version");
          
            Properties properties = Utility.getConfig();
           
            properties.setProperty("serial", dialog.getRegCode());
            Utility.saveConfig(properties);
            Main.setReg(result);
            setVisible(false);
            JOptionPane.showMessageDialog(null, result, "Registration", JOptionPane.INFORMATION_MESSAGE);
            dispose();


        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Code not accepted", "Error!", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LaterButton;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables
}
